### ISSUE TITLE
Losing a High Percent of Markers

### ISSUE THREAD

**Issue by Atvicenti** [browning-lab/flare#14]
Hello!

I've noticed a significant drop in markers from my input VCF file containing genotype data and the FLARE output VCF.

The min-maf/min-mac is set to 0, and there appears to be a significant number of markers in my reference.

Is the drop in markers expected? I am not sure if there is internal FLARE filtering, or if there may be something wrong with our pipeline.

Sorry if the question is pretty vague, but would appreciate any guidance!

**Comment by browning-lab** [comment]
Markers must be present in both the reference VCF file and the input VCF file in order to be analyzed.  Markers are considered the same if the VCF records in the reference and input VCF files have identical CHROM, POS, REF, and ALT fields.  Markers that are found in only in one of these two VCF files are not included in the flare output file.

**Comment by Atvicenti** [comment]
This makes perfect sense. 

Upon re-evaluation, I found there was significantly less overlap than expected between the reference and the input.

**Comment by GiuliaT94** [comment]
Hi, I was wondering if the only reasons why FLARE would drop markers would be due to the MAF threshold and/or the fact that the markers CHROM POS REF ALT do not match between the reference and the target. Would there be any other reason or regions of chromosomes where markers would be dropped?

**Comment by browning-lab** [comment]
There are three additional parameters that control the markers included in
the analysis: min-mac (default: min-mac=50), array (default: array=false),
and excludemarkers.
