### ISSUE TITLE
Convert the markers in a vcf to a bed file

### ISSUE THREAD

**Issue by LimingLiPU123** [browning-lab/flare#3]
Hi Brain,
Thank you for your work on Flare, it is much, much faster and space efficient than rfmix!  As we convert our workflows to using flare, we had a couple of questions on how to interpret and use the output.
The number of markers reported in the log file is much smaller than the number of vcf sites.  Are only unfixed markers considered/reported?
Currently, we utilize region estimates of ancestry in downstream analysis.  Do you have a suggestion on how to convert the markers in a vcf to a bed file that defines the admixture tracts by a specified ancestral population??  I realize it is ill-defined since there is no information between markers, but was hoping you had some previous experience with this using your model.
Thank you

**Comment by browning-lab** [comment]
Hello,
The number of markers in the output file is the number of markers included
in the analysis.  This number can be smaller than the number of input
markers because a MAF filter is applied.  This MAF filter is controlled by
flare's min-maf parameter.

Up to this point, we haven't had any occasion to convert the ancestries in
the output VCF file to ancestry tracts. So we don't know if there are any
existing tools that will perform this conversion.

-Brian
